name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install dvc dvc-gs pytest joblib scikit-learn numpy pandas cml

      # If your DVC remote is on GCS, add your service account JSON as a repo secret GCP_SA_KEY
      - name: Auth to GCP (for DVC on GCS)
        if: ${{ secrets.GCP_SA_KEY != '' }}
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_SA_KEY" > gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp-key.json" >> $GITHUB_ENV

      - name: DVC pull artifacts
        run: dvc pull -v

      - name: Run tests
        run: pytest -q

      - name: Build CI report
        run: |
          echo "## GA4 CI Report" > report.md
          echo "" >> report.md
          echo "✅ DVC pull & tests ran on \`${{ github.ref_name }}\`" >> report.md
          echo "" >> report.md
          echo "### Pytest summary" >> report.md
          echo '```' >> report.md
          pytest -q || true
          echo '```' >> report.md

      - name: Comment on PR with CML
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx cml comment report.md

