name: CI

on:
  pull_request:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest dvc[gs] google-cloud-storage

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: |
          gcloud config set project hybrid-shine-474105-e1
          gcloud auth list

      - name: DVC Pull
        run: |
          source .venv/bin/activate
          dvc pull -v

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest -v

      - name: Comment report with CML
        uses: iterative/setup-cml@v2
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "✅ Tests completed successfully!" > report.md
          cml comment create report.md

