# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest dvc dvc-gs

      - name: Check GCP_SA_KEY secret
        run: |
          if [ -z "${{ secrets.GCP_SA_KEY }}" ]; then
            echo "::error::GCP_SA_KEY secret is missing. Add it in GitHub → Settings → Secrets and variables → Actions."
            exit 1
          fi

      - name: Write GCP credentials & export env
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > $HOME/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

      - name: DVC pull artifacts
        run: dvc pull -v

      - name: Run tests
        run: pytest -q --disable-warnings --maxfail=1

      - name: Post CML comment
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pytest -q --disable-warnings --maxfail=1 --junitxml=report.xml || true
          echo "## GA4 CI Report" > report.md
          echo "" >> report.md
          echo "\`\`\`xml" >> report.md
          cat report.xml >> report.md
          echo "\`\`\`" >> report.md
          npx -y @dvcorg/cml@latest comment create --pr --commit-sha=${{ github.sha }} report.md

