name: GA4 CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps (pip + DVC + pytest)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install dvc dvc-gs pytest

      # Optional: authenticate to GCS if your DVC remote is on GCS
      - name: Configure GCS creds for DVC (optional)
        if: ${{ secrets.GCP_SA_KEY_JSON != '' }}
        env:
          GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
        run: |
          echo "$GCP_SA_KEY_JSON" > sa.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/sa.json" >> $GITHUB_ENV

      - name: DVC pull
        run: dvc pull -v

      - name: Run tests (pytest)
        run: pytest -q

      - name: Post CML report as PR comment
        if: ${{ github.event_name == 'pull_request' }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## GA4 CI Report" > report.md
          echo "" >> report.md
          echo "- Branch: $GITHUB_REF_NAME" >> report.md
          echo "- Commit: $GITHUB_SHA" >> report.md
          echo "" >> report.md
          echo "### Pytest summary" >> report.md
          pytest -q || true
          echo "" >> report.md
          npx -y @dvcorg/cml@latest comment create --pr report.md

